import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Sora } from 'next/font/google'
import SideMenu from '@/myComponents/SideMenu'

const inter = Sora({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>

        <div className="border-b bg-black/90 text-white ">
          <div className="flex h-16 items-center px-4 container mx-auto">
          phto-app
            <div className="ml-auto flex items-center space-x-4">
            <Avatar>
  <AvatarImage src="https://github.com/shadcn.png" />
  <AvatarFallback>CN</AvatarFallback>
</Avatar>

      
            </div>
          </div>
        </div>
        <div className='flex'>
          <SideMenu/>
        {children}</div></body>
    </html>
  )
}
